### ISSUE TITLE
Acuminator Nuget Package generates warnings

### ISSUE THREAD

**Issue by ghigad** [Acumatica/Acuminator#234] opened 2019-05-07 20:50 UTC
**Issue description:**
We tried to install Acuminator's Nuget package (`Acuminator.Analyzers`) on the Visual Studio project used for our Extensions in order to get Acuminator validations on build.  When we do so, we have many warnings (~30) saying that analyzer assemblies depend on assemblies that could not be found.

Here are a few examples of such warnings:

> Code:  IDE1003
>
> Analyzer assembly 'C:\Sources\Acumatica\Tests\TestExtension\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\PX.Data.dll' depends on 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.
>
> Analyzer assembly 'C:\Sources\Acumatica\Tests\TestExtension\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\PX.Data.dll' depends on 'Microsoft.Data.Services.Client, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.

Notes:
* My test project references a 2019R1U2 instance.
* Tested on Acuminator.Analyzers, version 1.6.1
* Using Visual Studio 2017 Professional (15.9.11)

**Steps to reproduce:**
* Add the `Acuminator.Analyzers` Nuget package to any standard Acumatica Extension Library project
  
**Expected result:**
* The project should build without errors or warnings related to the analyzers...  It should only reports errors and warnings generated by Acuminator.

**Actual result:**
* Many warnings are present on the project when the `Acuminator.Analyzers` Nuget package is installed on an Extension Library.

**Additional notes:**
* I tried to comment `Analyzer` elements added to the project by the `install.ps1` script like shown below.  The warnings went away and I could get Acuminator errors and warnings properly.

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- ... -->
  <ItemGroup>
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\Acuminator.Analyzers.dll" />
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\Acuminator.Utilities.dll" />
    <!--
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\CommonServiceLocator.dll" />
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\PX.BulkInsert.dll" />
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\PX.Common.dll" />
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\PX.Data.BQL.Fluent.dll" />
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\PX.Data.dll" />
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\PX.DbServices.dll" />
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\System.Runtime.InteropServices.RuntimeInformation.dll" />
    <Analyzer Include="..\packages\Acuminator.Analyzers.1.6.1\analyzers\dotnet\cs\System.ValueTuple.dll" />
    -->
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by dropsonic** [comment] 2019-05-08 08:55
Hi there,

Did you have this issue with the previous version of the package (v1.6.0)?

**Comment by dropsonic** [comment] 2019-05-13 11:40
@ghigad you can safely ignore these warnings. Seems that if you close and re-open the solution, the warnings disappear.
The cause of this issue is that Acuminator.Analyzers assembly depends on PX.Common, PX.Data and other Acumatica-related assemblies because Acuminator uses type information from them. They are included in the NuGet package, but each of these assemblies has its own dependency tree which is not included. Since no real code from PX.Data / PX.Common / other Acumatica-related assemblies is executed, these dependencies are not needed at all, so it is OK to skip these warnings.
We created a bug and will look into that later.

**Comment by ghigad** [comment] 2019-05-13 12:52
Hi @dropsonic,

Thank you for the follow-up.

I tried your solution.  When I close Visual Studio and reopen it, all the warnings reappear.   I need to Close the Solution (and leave Visual Studio open) and reopen the solution to make the warnings go away.  Unfortunately, when I build our solution, some warnings reappear.

It's not really acceptable for us to have warnings in our projets, so, for the moment, we will simply set this aside.

Can you give me a reference to the bug you opened so I can track it on my side and revisit this when it is fixed?

Thank you for your help!

Best regards!

**Comment by dropsonic** [comment] 2019-05-13 13:03
We track items in our internal JIRA which is not accessible from the outside, so I'll re-open this item so you could track the status. Sorry for the inconvenience.

**Comment by dropsonic** [comment] 2019-05-13 13:21
@ghigad another option is to disable IDE1003 warning temporarily

**Comment by dropsonic** [comment] 2019-06-06 07:31
Hi @ghigad,
We fixed this issue in the latest release (v1.6.2), please check.

**Comment by ghigad** [comment] 2019-06-18 13:37
Hi @dropsonic,

I tested the latest version (1.6.2) and we still have warning messages:

```
1>CSC : warning AD0001: Analyzer 'Acuminator.Analyzers.StaticAnalysis.LegacyBqlField.LegacyBqlFieldAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
1>CSC : warning AD0001: Analyzer 'Acuminator.Analyzers.StaticAnalysis.LegacyBqlField.LegacyBqlFieldAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
1>CSC : warning AD0001: Analyzer 'Acuminator.Analyzers.StaticAnalysis.LegacyBqlConstant.LegacyBqlConstantAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
1>CSC : warning AD0001: Analyzer 'Acuminator.Analyzers.StaticAnalysis.LegacyBqlConstant.LegacyBqlConstantAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
```

**Comment by dropsonic** [comment] 2019-06-18 15:07
@ghigad ok, we'll look into it.
Do you have another machine where you can try it? We were not able to reproduce it locally.

**Comment by ghigad** [comment] 2019-06-18 20:17
Hi @dropsonic,

I managed to reproduce it in different solutions and on different machines.

Tested:

* Windows 10 Pro 1703 French, Visual Studio 2017 Professional 15.9.12
* Windows 10 Pro 1803 French, Visual Studio 2017 Professional 15.9.12
* Windows Server 2016 1607 English, Visual Studio 2017 Professional 15.6.4

I tried to delete the ```.vs``` directory in my solution.

I also deleted the ``` %USERPROFILE%\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache``` directory and cleared the Nuget Cache (Clear All Nuget Cache(s) in the Nuget Package Manager options and ran ```NuGet.exe locals all -clear```).

Still got the warnings.

Any additional thoughts?

Thank you for your help!

Best regards

**Comment by dropsonic** [comment] 2019-06-19 07:11
@ghigad thanks!
Could you please attach a minimal VS solution where the issue reproduces? As far as I see from the csproj file posted above, we have some differences in its structure.

**Comment by ghigad** [comment] 2019-06-19 13:41
Hi @dropsonic ,

Attached is a sample project that shows this behavior ([AcceoBasePortal.zip](https://github.com/Acumatica/Acuminator/files/3306169/AcceoBasePortal.zip)) and the Visual Studio log file ([ActivityLog.zip](https://github.com/Acumatica/Acuminator/files/3306197/ActivityLog.zip)).

We get these warnings when we add the Nuget package to our existing extension project.

I also managed to reproduce it in a brand new solution (see [TestAcuminator2.zip](https://github.com/Acumatica/Acuminator/files/3306335/TestAcuminator2.zip) attached).  Here are the steps I followed:

1. Create new project (Class Library (.NET Framework))
2. Add ```Acuminator.Analyzers``` Nuget package to the new project
3. Build the project:  Note that no warning is produced
4. Add references to ```PX.Data.dll```, ```PX.Common.dll``` and ```PX.Objects.dll```
5. Build the project:  Note that the warnings are produced

Hope this helps!

Thank you for your help!

**Comment by dropsonic** [comment] 2019-06-19 15:18
@ghigad thanks, I was able to reproduce it locally!
We'll investigate it and come back with the results.

**Comment by ghigad** [comment] 2019-06-19 17:45
@dropsonic , thank you for the follow-up!

Glad you could reproduce it!

**Comment by ghigad** [comment] 2019-10-21 20:29
Hello @dropsonic,

Any news on this issue?

Thank you!

**Comment by dropsonic** [comment] 2019-10-22 14:02
Hi @ghigad,
It seems that we fixed the issue. The fix will be available in v2.1 which will be released in a day or two.

**Comment by ghigad** [comment] 2019-10-22 15:29
@dropsonic, thank you for the update!  Looking forward to test this!

**Comment by dropsonic** [comment] 2019-10-23 11:15
@ghigad v2.1.1 is available, please try and let us know whether it helped or not.
I wasn't able to reproduce the issue locally with this version.

**Comment by ghigad** [comment] 2019-10-23 12:16
Hello @dropsonic, Thank you for the update.  I tested version 2.1.1 and it works like a charm!  Thank you!

**Comment by dropsonic** [comment] 2019-10-23 12:19
@ghigad great!

**Closed by dropsonic** 2019-10-23 12:19 UTC
