### ISSUE TITLE
PX1094 with PXMappedCacheExtension

### ISSUE THREAD

**Issue by bhennelly** [Acumatica/Acuminator#323] opened 2019-11-20 15:12 UTC
Is it intended that we add PXHidden or PXCacheName to a PXMappedCacheExtension? Understanding it inherits from PXCacheExtension does it apply in this case as a mapped cache extension is used a little differently?

This is more of a question than an issue unless PX1094 should be ignored for PXMappedCacheExtension

**Comment by SENya1990** [comment] 2019-11-21 14:06
@bhennelly hi. Probably we shouldn't check PXMappedCacheExtension with this diagnostic. I will create a change request. I'll close this request when we implement the change

**Comment by SENya1990** [comment] 2020-01-24 19:56
the issue is fixed in upcoming version 2.1.3 with pull request
https://github.com/Acumatica/Acuminator/pull/334

**Closed by SENya1990** 2020-01-24 19:56 UTC
