### ISSUE TITLE
Error using 2.1.3.

### ISSUE THREAD

**Issue by ReTcepS** [Acumatica/Acuminator#352] opened 2020-03-06 13:44 UTC
Starting with version 2.1.3. I am getting an error. I am using Visual Studio 2017.

[I am not getting the error using 2.1.2.]

Error:
"System.MissingMethodException: Method not found: &apos;System.Threading.Tasks.Task`1&lt;System.ValueTuple`2&lt;Boolean,!!0&gt;&gt; Acuminator.Utilities.Common.ConcurrentExtensions.TryAwait(System.Threading.Tasks.Task`1&lt;!!0&gt;)&apos;.&#x000D;&#x000A; at Acuminator.Vsix.Coloriser.PXRoslynColorizerTagger.&lt;GetTagsAsyncImplementationAsync&gt;d__13.MoveNext()&#x000D;&#x000A; at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A; at Acuminator.Vsix.Coloriser.PXRoslynColorizerTagger.GetTagsAsyncImplementationAsync(ITextSnapshot snapshot, CancellationToken cToken)&#x000D;&#x000A; at Acuminator.Vsix.Coloriser.PXColorizerMainTagger.GetTagsAsyncImplementationAsync(ITextSnapshot snapshot, CancellationToken cancellationToken)&#x000D;&#x000A; at Acuminator.Vsix.Coloriser.BackgroundTagging.StartBackgroundTagging(PXColorizerTaggerBase tagger)&#x000D;&#x000A; at Acuminator.Vsix.Coloriser.PXColorizerTaggerBase.GetTagsAsync(ITextSnapshot snapshot)&#x000D;&#x000A; at Acuminator.Vsix.Coloriser.PXColorizerTaggerBase.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A; at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A; at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)"

**Comment by SENya1990** [comment] 2020-03-06 15:07
Hi @ReTcepS . 
We created a bug for this issue. 
Could you please provide the version of your Visual Studio (Help -> About Microsoft Visual Studio)

**Comment by SENya1990** [comment] 2020-03-06 15:09
Also if it is possible for you please try to use Acuminator on Visual Studio 2019

**Comment by ReTcepS** [comment] 2020-03-09 05:56
Hi @SENya1990,

Sorry for the delay, 
I am using Visual Studio Enterprise 2017, Version 15.9.20

I can't upgrade right now to Visual Studio 2019. 

Please tell me if it will be fixed for visual studio 2017. 

Thank you!

**Comment by SENya1990** [comment] 2020-03-09 16:40
Hi @ReTcepS. 
I investigated a bit. This is issue is VS 2017 only. Currently, we support both VS 2017 and VS 2019, therefore the issue will be fixed for VS 2017.

**Comment by ReTcepS** [comment] 2020-03-10 06:45
Hi @SENya1990 

Thank you for the information.

Please, let me know when it will be fixed.

**Comment by SENya1990** [comment] 2020-03-10 09:17
Hi @ReTcepS .
The issue is resolved in pull request https://github.com/Acumatica/Acuminator/pull/353
I attached a feature build of Acuminator with the fix. You can use it and test if the issue is resolved on your machine.
[Acuminator.zip](https://github.com/Acumatica/Acuminator/files/4311356/Acuminator.zip)

**Closed by SENya1990** 2020-03-10 09:17 UTC
Labels: bug

**Comment by tdhill-asf** [comment] 2020-03-10 16:25
Hi @SENya1990

I had this same issue as @ReTcepS and the build you attached solved the issue on my version of Visual Studio 2017 Pro.  

Thank you

**Comment by ReTcepS** [comment] 2020-03-10 18:26
Hi @SENya1990 

Also fixed on Visual Studio 2017 Enterprise,  Version 15.9.20.

Thank you!
