### ISSUE TITLE
False PX1029 when extending a DAC declared within a PXGraph

### ISSUE THREAD

**Issue by bhennelly** [Acumatica/Acuminator#289] opened 2019-09-17 20:46 UTC
The example we are working with is to extend the opportunity filter 'CreateSalesOrderFilter' which is declared within the OpportunityMaint graph. The existence of OpporutnityMaint in the dac extension throws message **PX1029 - PXGraph instances cannot be used inside DAC properties**.

Acuminator 2.0.0

Example code to recreate the issue:
```
[Serializable]
    public sealed class TestExtension : PXCacheExtension<PX.Objects.CR.OpportunityMaint.CreateSalesOrderFilter>
    {
      
    }
```

![image](https://user-images.githubusercontent.com/25390714/65078136-6bcf0180-d96a-11e9-8636-bdf4a3dcd1ec.png)

**Comment by SENya1990** [comment] 2019-09-18 19:26
@bhennelly this is a known issue in Acuminator. We filed it in our internal bug tracking system. I'll raise its priority. Thanks a lot for your help and sorry for the inconvenience. I will close this issue when the fix will be implemented.

**Comment by SENya1990** [comment] 2019-10-01 18:55
The issue is fixed in the pull request:
https://github.com/Acumatica/Acuminator/pull/294/files

**Closed by SENya1990** 2019-10-01 18:55 UTC
Labels: bug
